--APP_USER table
CREATE TABLE "ADMIN"."APP_USER" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD_HASH" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'user', 
	"AGE" NUMBER(3,0), 
	"NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTIFICATIONS" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"POSTAL_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_TIME" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	"ADDRESS" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "ADMIN"."UQ_APP_USER_EMAIL" ON "ADMIN"."APP_USER" ("EMAIL") 
  ;

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("EMAIL" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("ROLE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("NOTIFICATIONS" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" MODIFY ("FIRST_TIME" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."APP_USER" ADD CONSTRAINT "CK_APP_USER_NOTIFICATIONS" CHECK (notifications IN ('Y','N')) ENABLE;

ALTER TABLE "ADMIN"."APP_USER" ADD CONSTRAINT "CK_APP_USER_FIRST_TIME" CHECK (first_time IN ('Y','N')) ENABLE;

ALTER TABLE "ADMIN"."APP_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."APP_USER" ADD CONSTRAINT "UQ_APP_USER_EMAIL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE;

--CARTS table
CREATE TABLE "ADMIN"."CARTS" 
   (	"CART_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OPEN', 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"TOTAL_PRICE" NUMBER(12,2) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_CARTS_USER" ON "ADMIN"."CARTS" ("USER_ID") 
  ;

CREATE INDEX "ADMIN"."IX_CARTS_STATUS" ON "ADMIN"."CARTS" ("STATUS") 
  ;

ALTER TABLE "ADMIN"."CARTS" MODIFY ("CART_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CARTS" MODIFY ("USER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CARTS" MODIFY ("STATUS" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CARTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CARTS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CARTS" ADD CONSTRAINT "CK_CARTS_STATUS" CHECK (status IN ('OPEN','CLOSED','ABANDONED')) ENABLE;

ALTER TABLE "ADMIN"."CARTS" ADD CONSTRAINT "CK_CARTS_TOTAL_NONNEG" CHECK (total_price >= 0) ENABLE;

ALTER TABLE "ADMIN"."CARTS" ADD PRIMARY KEY ("CART_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."CARTS" ADD CONSTRAINT "FK_CARTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."APP_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

--CART_ITEMS table
CREATE TABLE "ADMIN"."CART_ITEMS" 
   (	"CART_ITEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CART_ID" NUMBER, 
	"ARTICLE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"QUANTITY" NUMBER(10,0) DEFAULT 1, 
	"PRICE" NUMBER(12,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_CART_ITEMS_CART" ON "ADMIN"."CART_ITEMS" ("CART_ID") 
  ;

CREATE UNIQUE INDEX "ADMIN"."UQ_CART_ITEMS_CART_ARTICLE" ON "ADMIN"."CART_ITEMS" ("CART_ID", "ARTICLE_ID") 
  ;

CREATE INDEX "ADMIN"."IX_CART_ITEMS_ARTICLE" ON "ADMIN"."CART_ITEMS" ("ARTICLE_ID") 
  ;

ALTER TABLE "ADMIN"."CART_ITEMS" MODIFY ("CART_ITEM_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CART_ITEMS" MODIFY ("CART_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CART_ITEMS" MODIFY ("ARTICLE_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CART_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CART_ITEMS" MODIFY ("PRICE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CART_ITEMS" ADD CONSTRAINT "CK_CART_ITEMS_QTY_POS" CHECK (quantity > 0) ENABLE;

ALTER TABLE "ADMIN"."CART_ITEMS" ADD CONSTRAINT "CK_CART_ITEMS_PRICE_NONNEG" CHECK (price >= 0) ENABLE;

ALTER TABLE "ADMIN"."CART_ITEMS" ADD PRIMARY KEY ("CART_ITEM_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."CART_ITEMS" ADD CONSTRAINT "UQ_CART_ITEMS_CART_ARTICLE" UNIQUE ("CART_ID", "ARTICLE_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."CART_ITEMS" ADD CONSTRAINT "FK_CART_ITEMS_CART" FOREIGN KEY ("CART_ID")
	  REFERENCES "ADMIN"."CARTS" ("CART_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "ADMIN"."CART_ITEMS" ADD CONSTRAINT "FK_CART_ITEMS_ARTICLE" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "ADMIN"."CATALOG" ("EXTERNAL_ARTICLE_ID") ENABLE;

--CATALOG table
CREATE TABLE "ADMIN"."CATALOG" 
   (	"DB_ARTICLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXTERNAL_ARTICLE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PROD_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE_NO" NUMBER, 
	"PRODUCT_TYPE_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"GRAPHICAL_APPEARANCE_NO" NUMBER, 
	"GRAPHICAL_APPEARANCE_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"COLOUR_GROUP_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"COLOUR_GROUP_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PERCEIVED_COLOUR_VALUE_ID" NUMBER, 
	"PERCEIVED_COLOUR_VALUE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PERCEIVED_COLOUR_MASTER_ID" NUMBER, 
	"PERCEIVED_COLOUR_MASTER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT_NO" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"INDEX_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INDEX_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"INDEX_GROUP_NO" NUMBER, 
	"INDEX_GROUP_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SECTION_NO" NUMBER, 
	"SECTION_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"GARMENT_GROUP_NO" NUMBER, 
	"GARMENT_GROUP_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL_DESC" CLOB COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER(12,2) DEFAULT 0, 
	"STOCK" NUMBER(10,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_CATALOG_PROD_NAME" ON "ADMIN"."CATALOG" ("PROD_NAME") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_STOCK" ON "ADMIN"."CATALOG" ("STOCK") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_DEPT_NAME" ON "ADMIN"."CATALOG" ("DEPARTMENT_NAME") 
  ;

CREATE UNIQUE INDEX "ADMIN"."UQ_CATALOG_EXTERNAL_ARTICLE" ON "ADMIN"."CATALOG" ("EXTERNAL_ARTICLE_ID") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_PRODUCT_CODE" ON "ADMIN"."CATALOG" ("PRODUCT_CODE") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_INDEX_GROUP" ON "ADMIN"."CATALOG" ("INDEX_GROUP_NAME") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_PRICE" ON "ADMIN"."CATALOG" ("PRICE") 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_PROD_NAME_LOWER" ON "ADMIN"."CATALOG" (LOWER("PROD_NAME")) 
  ;

CREATE INDEX "ADMIN"."IX_CATALOG_PTYPE_NAME" ON "ADMIN"."CATALOG" ("PRODUCT_TYPE_NAME") 
  ;

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("DB_ARTICLE_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("EXTERNAL_ARTICLE_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("PRODUCT_CODE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("PROD_NAME" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("PRICE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" MODIFY ("STOCK" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."CATALOG" ADD CONSTRAINT "CK_CATALOG_PRICE_NONNEG" CHECK (price >= 0) ENABLE;

ALTER TABLE "ADMIN"."CATALOG" ADD CONSTRAINT "CK_CATALOG_STOCK_NONNEG" CHECK (stock  >= 0) ENABLE;

ALTER TABLE "ADMIN"."CATALOG" ADD PRIMARY KEY ("DB_ARTICLE_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."CATALOG" ADD CONSTRAINT "UQ_CATALOG_EXTERNAL_ARTICLE" UNIQUE ("EXTERNAL_ARTICLE_ID")
  USING INDEX  ENABLE;

--ORDERS table
CREATE TABLE "ADMIN"."ORDERS" 
   (	"ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"ORDER_ADDRESS" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"TOTAL_PRICE" NUMBER(12,2) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_ORDERS_PAYM" ON "ADMIN"."ORDERS" (SYS_EXTRACT_UTC("PAYMENT_DATE")) 
  ;

CREATE INDEX "ADMIN"."IX_ORDERS_USER" ON "ADMIN"."ORDERS" ("USER_ID") 
  ;

ALTER TABLE "ADMIN"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDERS" MODIFY ("ORDER_ADDRESS" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDERS" ADD CONSTRAINT "CK_ORDERS_TOTAL_NONNEG" CHECK (total_price >= 0) ENABLE;

ALTER TABLE "ADMIN"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."ORDERS" ADD CONSTRAINT "FK_ORDERS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."APP_USER" ("USER_ID") ENABLE;

--ORDER_ITEMS table
CREATE TABLE "ADMIN"."ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_ID" NUMBER, 
	"ARTICLE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"QUANTITY" NUMBER(10,0) DEFAULT 1, 
	"PRICE" NUMBER(12,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_ORDER_ITEMS_ARTICLE" ON "ADMIN"."ORDER_ITEMS" ("ARTICLE_ID") 
  ;

CREATE INDEX "ADMIN"."IX_ORDER_ITEMS_ORDER" ON "ADMIN"."ORDER_ITEMS" ("ORDER_ID") 
  ;

ALTER TABLE "ADMIN"."ORDER_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDER_ITEMS" MODIFY ("PRICE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDER_ITEMS" ADD CONSTRAINT "CK_ORDER_ITEMS_QTY_POS" CHECK (quantity > 0) ENABLE;

ALTER TABLE "ADMIN"."ORDER_ITEMS" ADD CONSTRAINT "CK_ORDER_ITEMS_PRICE_NONNEG" CHECK (price >= 0) ENABLE;

ALTER TABLE "ADMIN"."ORDER_ITEMS" ADD PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."ORDER_ITEMS" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDER_ITEMS" MODIFY ("ARTICLE_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."ORDER_ITEMS" ADD CONSTRAINT "FK_ORDER_ITEMS_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ADMIN"."ORDERS" ("ORDER_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "ADMIN"."ORDER_ITEMS" ADD CONSTRAINT "FK_ORDER_ITEMS_ARTICLE" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "ADMIN"."CATALOG" ("EXTERNAL_ARTICLE_ID") ENABLE;

--PRODUCT_RATINGS table
CREATE TABLE "ADMIN"."PRODUCT_RATINGS" 
   (	"RATING_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"ARTICLE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER(1,0), 
	"REVIEW_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_PR_RATING" ON "ADMIN"."PRODUCT_RATINGS" ("RATING") 
  ;

CREATE INDEX "ADMIN"."IX_PR_USER" ON "ADMIN"."PRODUCT_RATINGS" ("USER_ID") 
  ;

CREATE UNIQUE INDEX "ADMIN"."UQ_PR_USER_ARTICLE" ON "ADMIN"."PRODUCT_RATINGS" ("USER_ID", "ARTICLE_ID") 
  ;

CREATE INDEX "ADMIN"."IX_PR_ARTICLE" ON "ADMIN"."PRODUCT_RATINGS" ("ARTICLE_ID") 
  ;

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" MODIFY ("RATING_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" MODIFY ("USER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" MODIFY ("ARTICLE_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" MODIFY ("RATING" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" MODIFY ("CREATED_AT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" ADD CONSTRAINT "CK_PR_RATING" CHECK (rating BETWEEN 1 AND 5) ENABLE;

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" ADD PRIMARY KEY ("RATING_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" ADD CONSTRAINT "UQ_PR_USER_ARTICLE" UNIQUE ("USER_ID", "ARTICLE_ID")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" ADD CONSTRAINT "FK_PR_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."APP_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "ADMIN"."PRODUCT_RATINGS" ADD CONSTRAINT "FK_PR_ARTICLE" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "ADMIN"."CATALOG" ("EXTERNAL_ARTICLE_ID") ON DELETE CASCADE ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_PRODUCT_RATINGS_UPD_TS" 
BEFORE UPDATE ON product_ratings
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "ADMIN"."TRG_PRODUCT_RATINGS_UPD_TS" ENABLE;

--PROMOS VECTOR TABLE
CREATE TABLE "ADMIN"."PROMO_PROMOS_COSINE" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"METADATA" JSON, 
	"EMBEDDING" VECTOR(384, FLOAT32)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "ADMIN"."PROMO_PROMOS_COSINE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

--USER_PREF_KV
CREATE TABLE "ADMIN"."USER_PREF_KV" 
   (	"USER_ID" NUMBER, 
	"FACET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"KEY_TEXT" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"WEIGHT" NUMBER(8,3) DEFAULT 0, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE INDEX "ADMIN"."IX_USER_PREF_KV_USER" ON "ADMIN"."USER_PREF_KV" ("USER_ID") 
  ;

CREATE UNIQUE INDEX "ADMIN"."PK_USER_PREF_KV" ON "ADMIN"."USER_PREF_KV" ("USER_ID", "FACET", "KEY_TEXT") 
  ;

ALTER TABLE "ADMIN"."USER_PREF_KV" MODIFY ("USER_ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."USER_PREF_KV" MODIFY ("FACET" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."USER_PREF_KV" MODIFY ("KEY_TEXT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."USER_PREF_KV" MODIFY ("WEIGHT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."USER_PREF_KV" MODIFY ("UPDATED_AT" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."USER_PREF_KV" ADD CONSTRAINT "CK_USER_PREF_KV_FACET" CHECK (
    facet IN ('GENDER','DEPARTMENT','PRODUCT_GROUP','SECTION','GARMENT_GROUP','COLOUR')
  ) ENABLE;

ALTER TABLE "ADMIN"."USER_PREF_KV" ADD CONSTRAINT "PK_USER_PREF_KV" PRIMARY KEY ("USER_ID", "FACET", "KEY_TEXT")
  USING INDEX  ENABLE;

ALTER TABLE "ADMIN"."USER_PREF_KV" ADD CONSTRAINT "FK_USER_PREF_KV_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."APP_USER" ("USER_ID") ON DELETE CASCADE ENABLE;

--PAYMENT RELATED TABLES
