-------------------------------------------------------------------------------
-- SCHEMA V3 — ORACLE 26 AI
-------------------------------------------------------------------------------

----------------------------
-- 1. APP_USER
----------------------------
CREATE TABLE ADMIN.APP_USER (
    USER_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
    EMAIL          VARCHAR2(255) NOT NULL,
    PASSWORD_HASH  VARCHAR2(255) NOT NULL,
    ROLE           VARCHAR2(50)  DEFAULT 'user' NOT NULL,
    AGE            NUMBER(3),
    NAME           VARCHAR2(150),
    NOTIFICATIONS  CHAR(1) DEFAULT 'N' NOT NULL,
    POSTAL_CODE    VARCHAR2(10),
    FIRST_TIME     CHAR(1) DEFAULT 'Y' NOT NULL,
    ADDRESS        VARCHAR2(300),
    CONSTRAINT PK_APP_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_APP_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_APP_USER_NOTIFICATIONS CHECK (notifications IN ('Y','N')),
    CONSTRAINT CK_APP_USER_FIRST_TIME CHECK (first_time IN ('Y','N'))
);


----------------------------
-- 2. CATALOG
----------------------------
CREATE TABLE ADMIN.CATALOG (
    DB_ARTICLE_ID                NUMBER GENERATED ALWAYS AS IDENTITY,
    EXTERNAL_ARTICLE_ID          VARCHAR2(30) NOT NULL,
    PRODUCT_CODE                 VARCHAR2(100) NOT NULL,
    PROD_NAME                    VARCHAR2(255) NOT NULL,
    PRODUCT_TYPE_NO              NUMBER,
    PRODUCT_TYPE_NAME            VARCHAR2(150),
    PRODUCT_GROUP_NAME           VARCHAR2(150),
    GRAPHICAL_APPEARANCE_NO      NUMBER,
    GRAPHICAL_APPEARANCE_NAME    VARCHAR2(150),
    COLOUR_GROUP_CODE            VARCHAR2(20),
    COLOUR_GROUP_NAME            VARCHAR2(100),
    PERCEIVED_COLOUR_VALUE_ID    NUMBER,
    PERCEIVED_COLOUR_VALUE_NAME  VARCHAR2(100),
    PERCEIVED_COLOUR_MASTER_ID   NUMBER,
    PERCEIVED_COLOUR_MASTER_NAME VARCHAR2(100),
    DEPARTMENT_NO                NUMBER,
    DEPARTMENT_NAME              VARCHAR2(150),
    INDEX_CODE                   VARCHAR2(50),
    INDEX_NAME                   VARCHAR2(150),
    INDEX_GROUP_NO               NUMBER,
    INDEX_GROUP_NAME             VARCHAR2(150),
    SECTION_NO                   NUMBER,
    SECTION_NAME                 VARCHAR2(150),
    GARMENT_GROUP_NO             NUMBER,
    GARMENT_GROUP_NAME           VARCHAR2(150),
    DETAIL_DESC                  CLOB,
    PRICE                        NUMBER(12,2) DEFAULT 0 NOT NULL,
    STOCK                        NUMBER(10)   DEFAULT 0 NOT NULL,
    IMAGE_URL                    VARCHAR2(1000),
    CONSTRAINT PK_CATALOG PRIMARY KEY (DB_ARTICLE_ID),
    CONSTRAINT UQ_CATALOG_EXTERNAL_ARTICLE UNIQUE (EXTERNAL_ARTICLE_ID),
    CONSTRAINT CK_CATALOG_PRICE_NONNEG CHECK (price >= 0),
    CONSTRAINT CK_CATALOG_STOCK_NONNEG CHECK (stock >= 0)
);

CREATE INDEX IX_CATALOG_PROD_NAME_LOWER ON ADMIN.CATALOG (LOWER(PROD_NAME));
CREATE INDEX IX_CATALOG_STOCK           ON ADMIN.CATALOG (STOCK);
CREATE INDEX IX_CATALOG_PRODUCT_CODE    ON ADMIN.CATALOG (PRODUCT_CODE);
CREATE INDEX IX_CATALOG_INDEX_GROUP     ON ADMIN.CATALOG (INDEX_GROUP_NAME);
CREATE INDEX IX_CATALOG_PRICE           ON ADMIN.CATALOG (PRICE);
CREATE INDEX IX_CATALOG_PTYPE_NAME      ON ADMIN.CATALOG (PRODUCT_TYPE_NAME);


----------------------------
-- 3. CARTS
----------------------------
CREATE TABLE ADMIN.CARTS (
    CART_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID       NUMBER NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    TOTAL_PRICE   NUMBER(12,2) DEFAULT 0 NOT NULL,
    PROMO_APPLIED CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_CARTS PRIMARY KEY (CART_ID),
    CONSTRAINT CK_CARTS_STATUS CHECK (status IN ('OPEN','CLOSED','ABANDONED')),
    CONSTRAINT CK_CARTS_PROMO CHECK (promo_applied IN ('Y','N')),
    CONSTRAINT CK_CARTS_TOTAL_NONNEG CHECK (total_price >= 0),
    CONSTRAINT FK_CARTS_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IX_CARTS_USER   ON ADMIN.CARTS (USER_ID);
CREATE INDEX IX_CARTS_STATUS ON ADMIN.CARTS (STATUS);


----------------------------
-- 4. CART_ITEMS
----------------------------
CREATE TABLE ADMIN.CART_ITEMS (
    CART_ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CART_ID      NUMBER NOT NULL,
    ARTICLE_ID   VARCHAR2(30) NOT NULL,
    QUANTITY     NUMBER(10) DEFAULT 1 NOT NULL,
    PRICE        NUMBER(12,2) NOT NULL,
    CONSTRAINT PK_CART_ITEMS PRIMARY KEY (CART_ITEM_ID),
    CONSTRAINT UQ_CART_ITEMS_CART_ARTICLE UNIQUE (CART_ID, ARTICLE_ID),
    CONSTRAINT CK_CART_ITEMS_QTY_POS CHECK (quantity > 0),
    CONSTRAINT CK_CART_ITEMS_PRICE_NONNEG CHECK (price >= 0),
    CONSTRAINT FK_CART_ITEMS_CART FOREIGN KEY (CART_ID)
        REFERENCES ADMIN.CARTS(CART_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEMS_ARTICLE FOREIGN KEY (ARTICLE_ID)
        REFERENCES ADMIN.CATALOG(EXTERNAL_ARTICLE_ID)
);

CREATE INDEX IX_CART_ITEMS_CART    ON ADMIN.CART_ITEMS (CART_ID);
CREATE INDEX IX_CART_ITEMS_ARTICLE ON ADMIN.CART_ITEMS (ARTICLE_ID);


----------------------------
-- 5. ORDERS
----------------------------
CREATE TABLE ADMIN.ORDERS (
    ORDER_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID       NUMBER NOT NULL,
    ORDER_ADDRESS VARCHAR2(300) NOT NULL,
    PAYMENT_DATE  TIMESTAMP WITH TIME ZONE,
    TOTAL_PRICE   NUMBER(12,2) DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT CK_ORDERS_TOTAL_NONNEG CHECK (total_price >= 0),
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID)
);

CREATE INDEX IX_ORDERS_USER ON ADMIN.ORDERS (USER_ID);
CREATE INDEX IX_ORDERS_PAYM ON ADMIN.ORDERS (SYS_EXTRACT_UTC(PAYMENT_DATE));


----------------------------
-- 6. ORDER_ITEMS
----------------------------
CREATE TABLE ADMIN.ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID      NUMBER NOT NULL,
    ARTICLE_ID    VARCHAR2(30) NOT NULL,
    QUANTITY      NUMBER(10) DEFAULT 1 NOT NULL,
    PRICE         NUMBER(12,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT CK_ORDER_ITEMS_QTY_POS CHECK (quantity > 0),
    CONSTRAINT CK_ORDER_ITEMS_PRICE_NONNEG CHECK (price >= 0),
    CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ADMIN.ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEMS_ARTICLE FOREIGN KEY (ARTICLE_ID)
        REFERENCES ADMIN.CATALOG(EXTERNAL_ARTICLE_ID)
);

CREATE INDEX IX_ORDER_ITEMS_ORDER   ON ADMIN.ORDER_ITEMS (ORDER_ID);
CREATE INDEX IX_ORDER_ITEMS_ARTICLE ON ADMIN.ORDER_ITEMS (ARTICLE_ID);


----------------------------
-- 7. INVOICESS  (Created BEFORE PAYMENTSS)
----------------------------
CREATE TABLE ADMIN.INVOICESS (
    INVOICE_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID     NUMBER NOT NULL,
    ORDER_ID    NUMBER NOT NULL,
    AMOUNT      NUMBER(12,2) NOT NULL,
    CURRENCY    VARCHAR2(10) DEFAULT 'MXN',
    STATUS      VARCHAR2(20) DEFAULT 'PAID',
    DESCRIPTION VARCHAR2(300),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_INVOICESS PRIMARY KEY (INVOICE_ID),
    CONSTRAINT CK_INVOICESS_AMOUNT CHECK (amount >= 0),
    CONSTRAINT FK_INVOICESS_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID),
    CONSTRAINT FK_INVOICESS_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ADMIN.ORDERS(ORDER_ID)
);

CREATE INDEX IX_INV_USER ON ADMIN.INVOICESS(USER_ID);


----------------------------
-- 8. PAYMENTSS  (Now valid)
----------------------------
CREATE TABLE ADMIN.PAYMENTSS (
    PAYMENT_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID            NUMBER NOT NULL,
    AMOUNT             NUMBER(12,2) NOT NULL,
    CURRENCY           VARCHAR2(10)  DEFAULT 'MXN',
    PAYMENT_PROVIDER   VARCHAR2(20)  DEFAULT 'STRIPE',
    PAYMENT_INTENT_ID  VARCHAR2(200) NOT NULL,
    STATUS             VARCHAR2(20)  DEFAULT 'PENDING',
    ORDER_ID           NUMBER,
    INVOICE_ID         NUMBER,
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_PAYMENTSS PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT UQ_PAYMENTSS_INTENT UNIQUE (PAYMENT_INTENT_ID),
    CONSTRAINT CK_PAYMENTSS_AMOUNT CHECK (amount >= 0),
    CONSTRAINT FK_PAYMENTSS_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PAYMENTSS_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ADMIN.ORDERS(ORDER_ID),
    CONSTRAINT FK_PAYMENTSS_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES ADMIN.INVOICESS(INVOICE_ID)
);

CREATE INDEX IX_PAYMENTSS_USER ON ADMIN.PAYMENTSS(USER_ID);


----------------------------
-- 9. PAYMENT_METHODSS
----------------------------
CREATE TABLE ADMIN.PAYMENT_METHODSS (
    METHOD_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID     NUMBER NOT NULL,
    BRAND       VARCHAR2(50),
    TYPE        VARCHAR2(50),
    LAST4       VARCHAR2(4),
    BANK        VARCHAR2(120),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_PAYMENT_METHODSS PRIMARY KEY (METHOD_ID),
    CONSTRAINT FK_PM_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IX_PM_USER ON ADMIN.PAYMENT_METHODSS(USER_ID);


----------------------------
-- 10. PRODUCT_RATINGS
----------------------------
CREATE TABLE ADMIN.PRODUCT_RATINGS (
    RATING_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID      NUMBER NOT NULL,
    ARTICLE_ID   VARCHAR2(30) NOT NULL,
    RATING       NUMBER(1) NOT NULL,
    REVIEW_TEXT  CLOB,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_PRODUCT_RATINGS PRIMARY KEY (RATING_ID),
    CONSTRAINT UQ_PR_USER_ARTICLE UNIQUE (USER_ID, ARTICLE_ID),
    CONSTRAINT CK_PR_RATING CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT FK_PR_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PR_ARTICLE FOREIGN KEY (ARTICLE_ID)
        REFERENCES ADMIN.CATALOG(EXTERNAL_ARTICLE_ID) ON DELETE CASCADE
);

CREATE INDEX IX_PR_USER    ON ADMIN.PRODUCT_RATINGS(USER_ID);
CREATE INDEX IX_PR_ARTICLE ON ADMIN.PRODUCT_RATINGS(ARTICLE_ID);


CREATE OR REPLACE TRIGGER ADMIN.TRG_PRODUCT_RATINGS_UPD_TS
BEFORE UPDATE ON ADMIN.PRODUCT_RATINGS
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/


----------------------------
-- 11. USER_PREF_KV
----------------------------
CREATE TABLE ADMIN.USER_PREF_KV (
    USER_ID     NUMBER NOT NULL,
    FACET       VARCHAR2(30) NOT NULL,
    KEY_TEXT    VARCHAR2(150) NOT NULL,
    WEIGHT      NUMBER(8,3) DEFAULT 0 NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PREF_KV PRIMARY KEY (USER_ID, FACET, KEY_TEXT),
    CONSTRAINT CK_USER_PREF_KV_FACET CHECK (
        facet IN ('GENDER','DEPARTMENT','PRODUCT_GROUP','SECTION','GARMENT_GROUP','COLOUR')
    ),
    CONSTRAINT FK_USER_PREF_KV_USER FOREIGN KEY (USER_ID)
        REFERENCES ADMIN.APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IX_USER_PREF_KV_USER ON ADMIN.USER_PREF_KV (USER_ID);


----------------------------
-- 12. PROMO_PROMOS_COSINE
----------------------------
CREATE TABLE ADMIN.PROMO_PROMOS_COSINE (
    ID        RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TEXT      CLOB,
    METADATA  JSON,
    EMBEDDING VECTOR(384, FLOAT32)
);

-------------------------------------------------------------------------------
-- END OF SCHEMA
-------------------------------------------------------------------------------
